# Generated by Django 4.1.5 on 2023-01-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_ticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="user",
            new_name="owner",
        ),
    ]
