# Generated by Django 4.1.5 on 2023-01-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_event_end_date_alter_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="api.event",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="api.event",
            ),
        ),
    ]
