# Generated by Django 4.1.5 on 2023-01-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_category_event_alter_package_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="packet",
            new_name="package",
        ),
    ]
