# Generated by Django 4.1.5 on 2023-02-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_packet_ticket_package"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-price"]},
        ),
    ]
