# Generated by Django 4.1.5 on 2023-02-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_event_options_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_date"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["price"]},
        ),
    ]
