# Generated by Django 4.1.5 on 2023-02-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_event_options_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(upload_to=""),
        ),
    ]
