# Generated by Django 4.1.5 on 2023-02-18 08:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_event_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=sorl.thumbnail.fields.ImageField(upload_to="event/thumbnail"),
        ),
    ]
