# Generated by Django 4.2.11 on 2024-08-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chat",
            name="single-chat-between-user-and-ticket",
        ),
        migrations.AlterField(
            model_name="chat",
            name="messages",
            field=models.JSONField(default=list),
        ),
    ]
