# Generated by Django 4.2.11 on 2024-07-26 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="buyer",
            new_name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("ticket", "owner")},
        ),
    ]
