# Generated by Django 4.2.11 on 2024-07-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_rename_buyer_chat_owner_alter_chat_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="messages",
            field=models.JSONField(default=dict),
        ),
    ]
