# Generated by Django 4.2.6 on 2024-07-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_confirmed",
        ),
    ]
