on:
  workflow_dispatch:
  push:
    branches:
    - production

jobs:
  django:
    name: Django build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Collect static files
      working-directory: ./backend/
      run: python manage.py collectstatic
    - name: Copy files over to the server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./backend
        remote: /home/${{ secrets.USERNAME }}/
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        privateKey: ${{ secrets.KEY }}
        username: ${{ secrets.USERNAME }}
    
